name: pop3
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/g0rdan/pop3

environment:
  sdk: '>=2.18.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  equatable: ^2.0.5
  rxdart: ^0.27.7
